### ISSUE TITLE
Kraken good accessibility - Completed

### ISSUE THREAD

**Issue by calistawascher** [calistawascher/kraken-good-accessibility#1]
@thatkidmadrid
[kraken-good-accessibility.zip](https://github.com/calistawascher/kraken-good-accessibility/files/7286891/kraken-good-accessibility.zip)
<img width="793" alt="markbot-screenshot" src="https://user-images.githubusercontent.com/77281286/136048784-c6fe517b-1ffd-401b-a69b-44c86e779b39.png">

**Comment by thatkidmadrid** [comment]
Hey Calista,

I wanted to remind you that you don't need to attach the zip of your code in the issue because it's already linked to your repository!

I think this is good and markbot isn't complaining about the structure, but I would be careful with how you structured things using `<article>`s. Usually `<article>`s [should be able to stand alone](https://www.w3schools.com/tags/tag_article.asp) so by wrapping the secondary header that contains the chapter and nav in an article may not make the most sense. I would put it inside the article that you set with `role="main"` but then wrap the content in a `div` and give that the `role="main"` instead

```
<body>
  <header role="banner"></header>
  <article>
    <header>...(this contains the main navigation with the role="navigation")</header>
    <div role="main">...</div>
    <footer>(this is the navigation footer)</footer>
  </article>
  <footer role="contentinfo">...</footer>
</body>
```
I'll give you the grade because everything else looks good and your descriptions make sense. Just be aware of the use of the `article` tag
